# Generated by Django 2.2.11 on 2020-03-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='gps_position',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='gps_position',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Location'),
            preserve_default=False,
        ),
    ]
