# Generated by Django 2.2.11 on 2020-03-20 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('loaded', models.DateTimeField()),
                ('delivered', models.DateTimeField()),
                ('product', models.CharField(max_length=600)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Buyer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Driver')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Seller')),
            ],
        ),
    ]
