# Generated by Django 2.2.11 on 2020-03-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200321_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='latidude',
            new_name='latitude',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='gps_position',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Location'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gps_position',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Location'),
        ),
    ]
