# Generated by Django 2.2.11 on 2020-03-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='product',
            new_name='transaction_content',
        ),
    ]
