# Generated by Django 2.2.11 on 2020-03-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200321_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('province', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Address'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Address'),
        ),
    ]
