# Generated by Django 2.2.11 on 2020-03-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200321_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='shop_category',
            field=models.CharField(choices=[('0', 'Sonstiges'), ('1', 'Lebensmittel'), ('2', 'Getränke'), ('3', 'Kleidung'), ('4', 'Schuhe'), ('5', 'Drogerie'), ('6', 'Optiker'), ('7', 'Haushaltswaren'), ('8', 'Elektronikwaren'), ('9', 'Outdoor & Sport'), ('10', 'Kunst & Musik'), ('11', 'Schreibwaren'), ('12', 'Geschenke'), ('13', 'Wäscherei'), ('14', 'Tabakwaren'), ('15', 'Spielzeugwaren')], default='0', max_length=2),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
