# Generated by Django 2.2.11 on 2020-03-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200321_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('0', 'Sonstiges'), ('1', 'Lebensmittel'), ('2', 'Getränke'), ('3', 'Kleidung'), ('4', 'Schuhe'), ('5', 'Drogerie'), ('6', 'Optiker'), ('7', 'Haushaltswaren'), ('8', 'Elektronikwaren'), ('9', 'Outdoor & Sport'), ('10', 'Kunst & Musik'), ('11', 'Schreibwaren'), ('12', 'Geschenke'), ('13', 'Wäscherei'), ('14', 'Tabakwaren'), ('15', 'Spielzeugwaren')], default='0', max_length=2),
        ),
    ]
