# Generated by Django 2.2.11 on 2020-03-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200321_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='products',
            field=models.TextField(),
        ),
    ]
