# Generated by Django 2.2.11 on 2020-03-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200321_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
    ]
