# Generated by Django 2.2.11 on 2020-03-21 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200321_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='products',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Seller')),
            ],
        ),
    ]
