# Generated by Django 2.2.11 on 2020-03-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200321_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='delivered',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='driver',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.Driver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='loaded',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
