# Generated by Django 2.2.11 on 2020-03-21 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200321_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Driver'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='loaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
